name: Testing

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  envs:
    name: Testing Env
    runs-on: ubuntu-latest
    steps:
    - name: Check out code base
      if: github.event_name == 'push'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check out code base
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Run wayback
      timeout-minutes: 2
      continue-on-error: true
      env:
        DEBUG: "on"
        WAYBACK_DAEMON: "web"
      uses: ./

  files:
    name: Testing Files
    runs-on: ubuntu-latest
    steps:
    - name: Check out code base
      if: github.event_name == 'push'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check out code base
      if: github.event_name == 'pull_request'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set configurations
      shell: bash
      run: |
        echo "${{ secrets.WAYBACK_CONFIGURATIONS }}" > wayback.conf
        cat wayback.conf

    - name: Run wayback
      timeout-minutes: 2
      continue-on-error: true
      env:
        DEBUG: "on"
        WAYBACK_DAEMON: "web"
      uses: ./
